### ISSUE TITLE
WPSCAN - High Memory Usage

### ISSUE THREAD

**Issue by ghost** [wpscanteam/wpscan#1687] opened 2021-11-16 11:05 UTC
I'm currently running a Wpscan against one of my clients websites and the wpscan process uses round about 5GB of memory to produce a 6.8 KB file, when I check the result content I noticed that the data_received_humanised is over 6GB

```json
{
  "stop_time": 1637057073,
  "elapsed": 229,
  "requests_done": 103,
  "cached_requests": 14,
  "data_sent": 33799,
  "data_sent_humanised": "33.007 KB",
  "data_received": 7326429514,
  "data_received_humanised": "6.823 GB",
  "used_memory": 294297600,
  "used_memory_humanised": "280.664 MB"
}
```

Command
```bash
wpscan --url <site-url> --random-user-agent --themes-threshold 0 --disable-tls-checks --ignore-main-redirect -e vp,vt,u --detection-mode passive --wp-version-detection mixed --interesting-findings-detection mixed -v -f json -o ./data.json
```

I've adjusted some parameters with no success, I've also tried running the command with no additional parameters and the memory usage remained te same 

Note: The scan used far more than 280MB, not sure why the large deficit 

Is there a way to ignore image data for example, as I suspect that a large amount of high quality images would potentially cause an issue like this?

**Comment by erwanlr** [comment] 2021-11-16 11:22
We don't feet image so the issue is not from there.

Given the high value of `data_received_humanised`, I guess some pages of the blog are quite large, or one is causing Nokogiri parsing to go nuts

Could you use a proxy (along with the --proxy option) and see if some page responses are massive ?

**Comment by alexsanford** [comment] 2023-09-14 18:56
User didn't respond, and it appears the account has been deleted. Closing.

**Closed by alexsanford** 2023-09-14 18:56 UTC
