### ISSUE TITLE
i get error wpscan json

### ISSUE THREAD

**Issue by melodyc89** [wpscanteam/wpscan#987] opened 2016-08-17 22:38 UTC
plugins.json: checksums do not match (local: cebb95092bc0441c248cf132149a85dff5f5dc8a773db674a4a6d8397e7a6199a29d29bad44788137c8676b95c7fd28139e8eceeb0b1fa3de93d1818204e6bf6 remote: 44cfc9a64e9f8c871d4821ff2285b7f48252e096a336d799b2ba11ad3974d846b4a1a4f0be7fd3695903c3ba2e36ef408fdc8bec18356830892dc09dbd912d13)

how i do fix it

**Comment by t0nylombardi** [comment] 2016-09-06 21:14
@melodyc89  This error looks like it has been resolved. Check the issue #981. which is the same problem.

**Comment by t0nylombardi** [comment] 2016-09-12 17:26
@FireFart @ethicalhack3r This issue should be closed since its a duplicate of #981

**Closed** 2016-09-12 17:28 UTC
