### ISSUE TITLE
404 checking

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#902] opened 2016-02-07 15:25 UTC
Received by mail:

Hi Team,

I made an interesting observation in https://github.com/wpscanteam/wpscan/blob/master/lib/wpscan/wp_target/wp_custom_directories.rb

If you look at like 29, you're testing to see if a response from the content directory test hashes to the error or home page:
```
return true if hash != error_404_hash and hash != homepage_hash
```

However, you don't do the same for line 45 when testing for the plugins directory -- i.e. you test to see if the code is a 404:
```
Browser.get(@uri.merge(wp_plugins_dir).to_s).code != 404
```

Why is extra check done for content dir but not for plugins dir?  

Any ideas why we are not doing this check @wpscanteam/owners ?

**Comment by mgites** [comment] 2016-02-08 22:34
Related, I understand the two lines represent different levels of caution.  I'm curious as whether it would make more sense to combine the two approaches by simply detecting both a 404 and 301 redirect using the status code (so also add ....code != 301) rather than hashing?

**Comment by mgites** [comment] 2016-02-08 23:04
I'm curious as to how common it is for sites to actually redirect on 404 to the home or custom 404 page and not actually return the 404 status code.  Last I checked, it's actually a poor SEO choice to do this kind of thing as it introduces duplicate content and subsequent penalties by Google.

**Comment by ethicalhack3r** [comment] 2016-02-10 08:51
You see all kinds of weird stuff when looking at web applications that defies all logic. It's common enough to do the check I think.

**Comment by FireFart** [comment] 2016-02-10 08:55
What do you think of smth like this?

```
def wp_plugins_dir_exists?
   resp = Browser.get(@uri.merge(wp_plugins_dir).to_s)
   if resp.code != 404
      hash = WebSite.page_hash(response)
      return true if hash != error_404_hash and hash != homepage_hash
   end
   return false
end
```

**Comment by ethicalhack3r** [comment] 2016-02-10 08:58
:+1: looks good to me!

**Comment by FireFart** [comment] 2016-02-10 08:58
nope it doesn't handle 403's correct....currently looking into it :D

**Comment by FireFart** [comment] 2016-02-10 09:02
Hm I think the current code in master is correct. Because every response on wp-content/plugins other than 404 is a hit (a forbidden, auth required, server error, ...). If it's a 404 the response code it's from the webserver I think, so it really does not exist.

So I don't think we need a change here. What do the others think?

**Comment by mgites** [comment] 2016-02-10 16:17
The issue is when performing brute force plugin look ups.

Isn't the issue that if you happen to lookup a nonexistent plugin subfolder in the wp-content/plugins folder (as brute force does to see if a plugin is installed) and a site redirects to home or some custom 404 page, a 404 code may not be returned. A false positive happens. Unfortunately, I have seen sites that would return a 200 code for something like: **http://www.example.com/wp-content/plugins/XVJ8PUNJOLZEG9VT68GQ0FPPBY4U.html**

The proposed change would now force the resulting page returned by a should-be-404-page, like above, to be tested against the home and custom 404.

**Comment by ethicalhack3r** [comment] 2016-02-10 16:32
I think we already do homepage and 404 hash checking for plugin/theme enumeration as it goes though this code https://github.com/wpscanteam/wpscan/blob/master/lib/common/models/wp_item/existable.rb

If there are still issues with false positives the ```--exclude-content-based "<regexp or string>"``` option can be used. This options does the following:

```
Used with the enumeration option, will exclude all occurrences based on the regexp or string supplied.
You do not need to provide the regexp delimiters, but you must write the quotes (simple or double).
```

**Comment by erwanlr** [comment] 2016-02-10 17:13
This issue has nothing to do with plugins/themes detection, it just checks whether the wp-content & wp-plugins directory exists and that's all.

However, like Ryan said above, we do perform similar checks about the 404 hashes during the plugins/themes enumeration. Regarding that, I responded on the other issue thread (#903).

**Comment by ethicalhack3r** [comment] 2016-06-07 14:28
Closing as I don't think there's anything to be done here

**Closed by ethicalhack3r** 2016-06-07 14:28 UTC
