### ISSUE TITLE
Stream error in the HTTP/2 framing layer

### ISSUE THREAD

**Issue by SaifKhaan** [wpscanteam/wpscan#1624] opened 2021-03-27 17:52 UTC
SITE IS UP
wpscan version: 3.8.17
wpscan --url https://success.zomato.com/
Scan Aborted: The url supplied 'https://success.zomato.com/' seems to be down (Stream error in the HTTP/2 framing layer)
not using proxy

**Comment by erwanlr** [comment] 2021-03-30 07:27
What's your version of `curl` ? `curl --version` If not the latest, or at least 7.72, please update (https://github.com/wpscanteam/wpscan#prerequisites)

**Comment by emgaurav** [comment] 2022-05-02 07:38
anyone found a solution yet??

**Comment by alexsanford** [comment] 2023-09-21 20:06
Looks like the `https://success.zomato.com/` URL is no longer valid. Is there another URL we could use to try to reproduce this error?

**Comment by alexsanford** [comment] 2023-09-29 14:33
I was able to reproduce this (sporadically) for a misbehaving website on my end. It seems to be due to a malformed TLS response that curl is trying to handle.

I tested on Ubuntu 22.04 with curl `7.81.0` and MacOS Ventura with curl `8.1.2`. When using the newer curl version, I was only able to reproduce the error when using the `--random-user-agent` option, which may have been what was causing this particular website to return malformed responses. The older version of curl seemed to have more frequent problems.

I'll also note that I was thinking that this might be an HTTP/2-specific issue, but I messed around with HTTP/1.1 and got an error in this case as well: `Failure when receiving data from the peer`.

So I think the solution to this is to use the newest version of curl that you can, as the newer versions seem to handle these sorts of issues better. And otherwise to play around with options to see what works for the specific website.

Closing this for now. If we can get a site that consistently causes this error for the latest version of `curl`, then it would be worth looking into further.

**Closed by alexsanford** 2023-09-29 14:33 UTC
Labels: needs info
