### ISSUE TITLE
Using wpscan with proxychains

### ISSUE THREAD

**Issue by surfer190** [wpscanteam/wpscan#810] opened 2015-04-26 08:30 UTC
When using wpscan with a `proxychains`

It usually gives:

```
The WordPress URL supplied <site> seems to be down.
```

Even when I increase the timeouts:

```
proxychains ruby wpscan.rb --url <site> --connect-timeout 10 --request-timeout 10
```

**Comment by mrnfrancesco** [comment] 2015-06-03 14:59
Cannot reproduce the issue, it works fine by me.

What is `<site>`? Could the website itself to have problems instead of wpscan?

**Comment by ethicalhack3r** [comment] 2015-06-18 15:03
Closing due to unable to reproduce. Can re-open if other users have the same issue.

**Closed by ethicalhack3r** 2015-06-18 15:03 UTC
