### ISSUE TITLE
Parsable output

### ISSUE THREAD

**Issue by sourcerer-mike** [wpscanteam/wpscan#870] opened 2015-10-04 07:26 UTC
Please make the output parsable or in another form (XML, JSON, YML).
As a developer I like to scan my sites an write my own evaluation for the results, so that I can pretty-print it and only send to me on specific events.

**Comment by ethicalhack3r** [comment] 2015-10-05 11:22
Hi, this is a duplicate of https://github.com/wpscanteam/wpscan/issues/198

Please read and if necessary comment on that thread regarding this feature request

**Closed by ethicalhack3r** 2015-10-05 11:22 UTC
